export const INBOX_ROUTE = '/mail/inbox'
export const SENT_ROUTE = '/mail/sent'
export const DRAFTS_ROUTE = '/mail/drafts'
export const TRASH_ROUTE = '/mail/trash' 
export const SPAM_ROUTE = '/mail/spam'
